import type { User, Project, Issue } from '@/types'

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'admin@example.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-2',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    role: 'developer',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user-3',
    email: 'jane.smith@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    role: 'manager',
    createdAt: new Date('2024-02-01'),
  },
]

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Website Redesign',
    identifier: 'website-redesign',
    description: 'Complete overhaul of the company website',
    status: 'active',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'proj-2',
    name: 'Mobile App',
    identifier: 'mobile-app',
    description: 'iOS and Android mobile application',
    status: 'active',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'proj-3',
    name: 'API Integration',
    identifier: 'api-integration',
    description: 'Third-party API integrations',
    status: 'active',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-25'),
  },
]

export const mockIssues: Issue[] = [
  {
    id: 'issue-1',
    projectId: 'proj-1',
    tracker: 'bug',
    subject: 'Homepage loading slow on mobile',
    description: 'The homepage takes more than 5 seconds to load on mobile devices',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'user-2',
    authorId: 'user-3',
    dueDate: new Date('2024-04-01'),
    estimatedHours: 8,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'issue-2',
    projectId: 'proj-1',
    tracker: 'feature',
    subject: 'Add dark mode support',
    description: 'Implement dark mode toggle for the entire website',
    status: 'new',
    priority: 'normal',
    assigneeId: null,
    authorId: 'user-1',
    dueDate: new Date('2024-04-15'),
    estimatedHours: 16,
    createdAt: new Date('2024-03-12'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: 'issue-3',
    projectId: 'proj-2',
    tracker: 'bug',
    subject: 'App crashes on login',
    description: 'The app crashes when users try to log in with Google',
    status: 'new',
    priority: 'urgent',
    assigneeId: 'user-2',
    authorId: 'user-3',
    dueDate: new Date('2024-03-25'),
    estimatedHours: 4,
    createdAt: new Date('2024-03-18'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: 'issue-4',
    projectId: 'proj-2',
    tracker: 'task',
    subject: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment',
    status: 'resolved',
    priority: 'normal',
    assigneeId: 'user-2',
    authorId: 'user-1',
    dueDate: null,
    estimatedHours: 12,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'issue-5',
    projectId: 'proj-3',
    tracker: 'feature',
    subject: 'Implement Stripe payment integration',
    description: 'Add Stripe as a payment provider for subscriptions',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'user-2',
    authorId: 'user-3',
    dueDate: new Date('2024-04-10'),
    estimatedHours: 24,
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-20'),
  },
]
